#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fsarchiver
Version  : 0.8.6
Release  : 1
URL      : https://github.com/fdupoux/fsarchiver/releases/download/0.8.6/fsarchiver-0.8.6.tar.gz
Source0  : https://github.com/fdupoux/fsarchiver/releases/download/0.8.6/fsarchiver-0.8.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fsarchiver-bin = %{version}-%{release}
Requires: fsarchiver-license = %{version}-%{release}
Requires: fsarchiver-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : libgcrypt-dev
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(e2p)
BuildRequires : pkgconfig(ext2fs)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(lzo2)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : zstd-dev

%description
FSArchiver is a system tool that allows you to save the contents of a
filesystem to a compressed archive file. The filesystem contents can be
restored on a device which has a different size and it can be restored on a
different filesystem. Unlike tar/dar, FSArchiver also creates the
filesystem when it extracts the data to devices. Everything is checksummed
in the archive in order to protect the data. If the archive is corrupt, you
just lose the current file, not the whole archive.

%package bin
Summary: bin components for the fsarchiver package.
Group: Binaries
Requires: fsarchiver-license = %{version}-%{release}

%description bin
bin components for the fsarchiver package.


%package license
Summary: license components for the fsarchiver package.
Group: Default

%description license
license components for the fsarchiver package.


%package man
Summary: man components for the fsarchiver package.
Group: Default

%description man
man components for the fsarchiver package.


%prep
%setup -q -n fsarchiver-0.8.6
cd %{_builddir}/fsarchiver-0.8.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662507835
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1662507835
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fsarchiver
cp %{_builddir}/fsarchiver-%{version}/COPYING %{buildroot}/usr/share/package-licenses/fsarchiver/2d29c273fda30310211bbf6a24127d589be09b6c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsarchiver

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fsarchiver/2d29c273fda30310211bbf6a24127d589be09b6c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/fsarchiver.8
